### ISSUE TITLE
Помогите я не могу подключить её, 

### ISSUE THREAD

**Issue by Kovriga** [PNKBizz/vue-yandex-maps#11]
![image](https://user-images.githubusercontent.com/60592893/189880099-e2a2cbf3-8ed6-4148-8d8d-6091a9223e46.png)

**Comment by Kovriga** [comment]
<template>
  <div class="main-component">
    <div>
      <div v-for="(item, index) in allPost" :key="index" class="main-component--item">
        <div class="main-component--item-image">
          <div class="main-component--item-image-main">
            <img :src="item.images[0].path"
                 width="412" height="240">
          </div>
          <div class="main-component--item-image-child" >
            <img :src="itemPhoto.path" width="162" height="112" v-for="(itemPhoto, index2) in item.images" :key="index2">
          </div>
        </div>
        <div v-if="mapVisible === item.id">
          <YandexMap :settings="settings" :coordinates="[32, 50]">
            
          </YandexMap>
        </div>

        <div v-else class="main-component--item-content">
          <div class="main-component--item-content--header">
            <div>
              <h3>{{ item.name }}</h3>
              <p>{{ item.address }}</p>
            </div>
            <div class="button-location" @click="mapVisibleEdit(item.id)">
              <div>
                <svg width="18" height="24" viewBox="0 0 18 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" clip-rule="evenodd"
                        d="M9 24C9 24 18 15.471 18 9C18 6.61305 17.0518 4.32387 15.364 2.63604C13.6761 0.948211 11.3869 0 9 0C6.61305 0 4.32387 0.948211 2.63604 2.63604C0.948211 4.32387 3.55683e-08 6.61305 0 9C0 15.471 9 24 9 24ZM9 13.5C10.1935 13.5 11.3381 13.0259 12.182 12.182C13.0259 11.3381 13.5 10.1935 13.5 9C13.5 7.80653 13.0259 6.66193 12.182 5.81802C11.3381 4.97411 10.1935 4.5 9 4.5C7.80653 4.5 6.66193 4.97411 5.81802 5.81802C4.97411 6.66193 4.5 7.80653 4.5 9C4.5 10.1935 4.97411 11.3381 5.81802 12.182C6.66193 13.0259 7.80653 13.5 9 13.5Z"
                        fill="white"/>
                </svg>
              </div>
            </div>
          </div>
          <div class="main-component--item-content--content">
            <div>
              <p>Занято номеров:</p>
              <p>Класс:</p>
              <p>Расположение</p>
            </div>
            <div>
              <p>{{ item.freeRooms }}/{{ item.allRooms }}</p>
              <p>{{ item.roomClass }}</p>
              <p>{{ item.distanceFromCenter }} км от центра</p>
            </div>
          </div>
          <div class="main-component--item-content--action">
            <p>от 49 800 р. за 41 день</p>
            <div class="button-info">
              <p>ПОДРОБНЕЕ</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import {Options, Vue} from "vue-class-component";
import axios, {AxiosResponse} from "axios";

@Options({
  components: {}
})

export default class MainComponent extends Vue {

  mapVisible: number|null = null;
  allPost = [];
  settings = {
    apiKey: '8927a5f1-772e-480b-bf79-65fa7e9d2cf8', // Индивидуальный ключ API
    lang: 'ru_RU', // Используемый язык
    coordorder: 'latlong', // Порядок задания географических координат
    debug: false, // Режим отладки
    version: '2.1' // Версия Я.Карт
  }
  coordinates = [55, 33];
  controls = ['fullscreenControl'];
  detailedControls = { zoomControl: { position: { right: 10, top: 50 } } };
  created(): void {
    axios.get('http://localhost:3000/posts').then((response: AxiosResponse) => {

      this.allPost = response.data;
    })
  }

**Comment by Kovriga** [comment]
`<template>
  <div class="main-component">
    <div>
      <div v-for="(item, index) in allPost" :key="index" class="main-component--item">
        <div class="main-component--item-image">
          <div class="main-component--item-image-main">
            <img :src="item.images[0].path"
                 width="412" height="240">
          </div>
          <div class="main-component--item-image-child" >
            <img :src="itemPhoto.path" width="162" height="112" v-for="(itemPhoto, index2) in item.images" :key="index2">
          </div>
        </div>
        <div v-if="mapVisible === item.id">
          <YandexMap :settings="settings" :coordinates="[32, 50]">
            
          </YandexMap>
        </div>

        <div v-else class="main-component--item-content">
          <div class="main-component--item-content--header">
            <div>
              <h3>{{ item.name }}</h3>
              <p>{{ item.address }}</p>
            </div>
            <div class="button-location" @click="mapVisibleEdit(item.id)">
              <div>
                <svg width="18" height="24" viewBox="0 0 18 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" clip-rule="evenodd"
                        d="M9 24C9 24 18 15.471 18 9C18 6.61305 17.0518 4.32387 15.364 2.63604C13.6761 0.948211 11.3869 0 9 0C6.61305 0 4.32387 0.948211 2.63604 2.63604C0.948211 4.32387 3.55683e-08 6.61305 0 9C0 15.471 9 24 9 24ZM9 13.5C10.1935 13.5 11.3381 13.0259 12.182 12.182C13.0259 11.3381 13.5 10.1935 13.5 9C13.5 7.80653 13.0259 6.66193 12.182 5.81802C11.3381 4.97411 10.1935 4.5 9 4.5C7.80653 4.5 6.66193 4.97411 5.81802 5.81802C4.97411 6.66193 4.5 7.80653 4.5 9C4.5 10.1935 4.97411 11.3381 5.81802 12.182C6.66193 13.0259 7.80653 13.5 9 13.5Z"
                        fill="white"/>
                </svg>
              </div>
            </div>
          </div>
          <div class="main-component--item-content--content">
            <div>
              <p>Занято номеров:</p>
              <p>Класс:</p>
              <p>Расположение</p>
            </div>
            <div>
              <p>{{ item.freeRooms }}/{{ item.allRooms }}</p>
              <p>{{ item.roomClass }}</p>
              <p>{{ item.distanceFromCenter }} км от центра</p>
            </div>
          </div>
          <div class="main-component--item-content--action">
            <p>от 49 800 р. за 41 день</p>
            <div class="button-info">
              <p>ПОДРОБНЕЕ</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import {Options, Vue} from "vue-class-component";
import axios, {AxiosResponse} from "axios";

@Options({
  components: {}
})

export default class MainComponent extends Vue {

  mapVisible: number|null = null;
  allPost = [];
  settings = {
    apiKey: '8927a5f1-772e-480b-bf79-65fa7e9d2cf8', // Индивидуальный ключ API
    lang: 'ru_RU', // Используемый язык
    coordorder: 'latlong', // Порядок задания географических координат
    debug: false, // Режим отладки
    version: '2.1' // Версия Я.Карт
  }
  coordinates = [55, 33];
  controls = ['fullscreenControl'];
  detailedControls = { zoomControl: { position: { right: 10, top: 50 } } };
  created(): void {
    axios.get('http://localhost:3000/posts').then((response: AxiosResponse) => {

      this.allPost = response.data;
    })
  }
`

**Comment by Kovriga** [comment]
Можно более подробную инструкцию по использованию?) Я просто тупой

**Comment by Kovriga** [comment]
Напишите пожалуйста что и куда добавлять, к примеру, этот код в main.ts этот в App.vue

**Comment by PNKBizz** [comment]
Ну вы хоть примеры компонентов прикрепите что-ли

**Comment by Kovriga** [comment]
`import {Options, Vue} from "vue-class-component";
import axios, {AxiosResponse} from "axios";
import {YandexMap} from "vue-yandex-maps";

@Options({
  components: {YandexMap}
})

export default class MainComponent extends Vue {

  mapVisible: number|null = null;
  allPost = [];

  created(): void {
    axios.get('http://localhost:3000/posts').then((response: AxiosResponse) => {

      this.allPost = response.data;
    })
  }`

**Comment by Kovriga** [comment]
![image](https://user-images.githubusercontent.com/60592893/189894208-3e9063a6-8b24-426f-a3bb-7e8bfcd5e5cb.png)

**Comment by Kovriga** [comment]
Попытался просто в тупую пример применить

**Comment by Kovriga** [comment]
![image](https://user-images.githubusercontent.com/60592893/189902835-d2d284c7-5bb4-45d3-8d70-885ef6eda253.png)

**Comment by Kovriga** [comment]
<template>
  <yandexMap
      :settings = "settings"
      :coordinates="coordinates"
      :detailed-controls="detailedControls"
      :controls="controls"
      map-type="hybrid"
  />
</template>

<script lang="ts">
import { yandexMap } from 'vue-yandex-maps'
import {Options, Vue} from "vue-class-component";

@Options({yandexMap})

export default class VueMapCom extends Vue{
  coordinates = [55, 33];
  controls = ['fullscreenControl'];
  detailedControls = { zoomControl: { position: { right: 10, top: 50 } } };
  settings = {
    apiKey: '8927a5f1-772e-480b-bf79-65fa7e9d2cf8', // Индивидуальный ключ API
    lang: 'ru_RU', // Используемый язык
    coordorder: 'latlong', // Порядок задания географических координат
    debug: false, // Режим отладки
    version: '2.1' // Версия Я.Карт
  }

}
</script>

<style>
.yandex-container {
  height: 400px;
}
</style>

**Comment by PNKBizz** [comment]
vue-class-component не надо использовать. Пишите на третьем вью
