### ISSUE TITLE
declare module vue-yandex-maps

### ISSUE THREAD

**Issue by Flareonn** [PNKBizz/vue-yandex-maps#14]
![image](https://user-images.githubusercontent.com/35931685/195521653-69351a6d-ce6e-4f75-b9a5-cf23ef10afba.png)

- dependencies
  - "vue": "^3.2.40",
  - "vue-yandex-maps": "^1.0.4"
- "devDependencies": 
  - "@types/node": "^18.7.13",
  - "@vitejs/plugin-vue": "^3.0.3",
  - "typescript": "^4.6.4",
  - "vite": "^3.0.7",
  - "vue-tsc": "^1.0.0-rc.5"
  
Отображает такую ошибку при импорте YmapPlugin, в моменте глобальной регистрации компонента

**Comment by PNKBizz** [comment]
Загрузите весь код в репозиторий и прикрепите ссылку

**Comment by ikloster03** [comment]
Привет, @PNKBizz, пожалуйста, смержи мой пулл-реквест #27, он решает данную проблему

**Comment by PNKBizz** [comment]
Должно быть исправлено в версии 1.0.5
