### ISSUE TITLE
Импорт текущего инстанса леадера

### ISSUE THREAD

**Issue by spokik** [PNKBizz/vue-yandex-maps#15]
На данный момент у нас есть возможность импортировать лоадер.  При этом, насколько я посмотрел проект, сам инстанс нигде не сохраняется, лишь его экземпляр используется в  [src/Map.ts](https://github.com/PNKBizz/vue-yandex-maps/blob/master/src/Map.ts)

Как-то неудобно каждый раз создавать его передавая настройки. Их же тоже нужно импортировать.

**Comment by PNKBizz** [comment]
Лоадер нужен один раз. Для загрузки и начальной инициализации. Далее по всему проекту доступна переменная `ymaps` и лоадер  больше не нужен. Если я правильно понял проблему

**Comment by spokik** [comment]
Действительно. Разобрался. Вынес это все в main.js 

Вероятно об этом можно написать в доке. Мне было не очевидно. Чутка запутался. Большое спасибо. Теперь выглядит много лучше! 👍
