### ISSUE TITLE
How to change marker position

### ISSUE THREAD

**Issue by drev74** [PNKBizz/vue-yandex-maps#17]
Hello I'd like to change marker position on each click, as it was impl in `v0.x` from [here](https://vue-yandex-maps.github.io/en/examples/#custom-icon):
```vue
// v0.x works
<template>
  <yandex-map :coords="coords">
    <ymap-marker 
      marker-id="123" 
      :coords="coords"
      :icon="markerIcon"
    />
  </yandex-map>
</template>
```
When I impl the same func on `v1.x`, I'm getting an event with coords, but the marker does not change its position:
```vue
// v1.x doesn't work
<template>
  <yandex-map
    :settings="settings"
    :coordinates="center"
    :zoom="zoom"
    @click="onMapClick"
  >
    <yandex-marker
      :marker-id="123"
      :coordinates="center"    
      @click="onMarkerClick"
    />
  </yandex-map>
</template>
```

**Comment by PNKBizz** [comment]
Hi! Please create repo with your code

**Comment by drev74** [comment]
> Hi! Please create repo with your code

You already have an example [here](https://vue-yandex-maps.github.io/examples/#%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BC%D0%B0%D1%80%D0%BA%D0%B5%D1%80%D0%B0-%D0%BF%D0%BE-%D0%BA%D0%BB%D0%B8%D0%BA%D1%83)

You can't move a cursor on the TS map with [this](https://vue-yandex-maps.github.io/new-docs/examples/markers.html) example

I'd personally like to use the TS version. However, had to fallback to 0x due to this limitation

**Comment by Alekenzy** [comment]
Привет! Этот вопрос все еще актуален. Пробовал изменить координаты маркера - а все то же самое.

Есть ли какое-нибудь решение или другой способ достичь реактивности маркера?

**Comment by PNKBizz** [comment]
Shame on me. Examples in docs are from old version. I'll fix it asap

**Comment by PNKBizz** [comment]
@Alekenzy нужен пример кода. Маркеры реактивные по-умолчанию

**Comment by drev74** [comment]
I don't see any functional changes. Upd marker position on click still doesn't work. Your upd to docs points to old documentation :roll_eyes:
