### ISSUE TITLE
YandexClusterer

### ISSUE THREAD

**Issue by Islomzoda** [PNKBizz/vue-yandex-maps#18]
было бы не плохо если бы добавили минимальный пример для использование 
YandexClusterer

**Comment by PNKBizz** [comment]
Ок. Постараюсь добавить в ближайшее время

**Comment by Islomzoda** [comment]
круто скажи пожалуйста можно ли тут сделать что то вроде динамическое добавление меток и удаление по клику наметку и все сразу ?

**Comment by PNKBizz** [comment]
Можно сделать все, что позволяет АПИ Я.Карт )

**Comment by PNKBizz** [comment]
https://vue-yandex-maps.github.io/new-docs/examples/clusterer.html

**Comment by danilabais** [comment]
Привет, подскажи, пожалуйста, как можно подписаться на клик по YandexCluster?
