### ISSUE TITLE
Sources path

### ISSUE THREAD

**Issue by drev74** [PNKBizz/vue-yandex-maps#19]
Hello

I'm confused about your versioning for Vue 3 :confused: 

npm install vue-yandex-maps@next - Next version
npm install vue-yandex-maps@beta - Beta version

If I open [the repo](https://github.com/PNKBizz/vue-yandex-maps) I see only one version, which is `beta`. I wanna work with  the `next` version. Where can I find sources for it? :thinking:

**Comment by PNKBizz** [comment]
https://github.com/PNKBizz/vue-yandex-map

**Comment by PNKBizz** [comment]
vue3-only
