### ISSUE TITLE
Не отключается интерактивность 

### ISSUE THREAD

**Issue by spokik** [PNKBizz/vue-yandex-maps#20]
В прошлой версии был аналогичный закрытый [вопрос](https://github.com/pnkbizz/vue-yandex-map/issues/385?ref=https://coder.social).
Там же есть событие, которое возвращает созданный инстанс карты.

Я разобрался как повторить в этой версии, однако хочется дополнительный пример в документации  по добавлению опций из [яндекс API](https://yandex.ru/dev/maps/jsapi/doc/2.1/ref/reference/Map.html#param-options.yandexMapDisablePoiInteractivity?from=SO).

P.s.
Честно говоря было совсем не очевидно, что получить инстанс можно таким путем. А другим я не нашел.

**Comment by PNKBizz** [comment]
Не очень понял вопрос. Карта эмитит событие `created`, в нем инстанс карты. Дальше с ним можно делать все, что угодно.

**Comment by spokik** [comment]
Просто просьба добавить такой пример доку. Просто часто гайдах options устанавливаются в момент [создания экземпляра](https://ru.stackoverflow.com/questions/758207/Отключить-интерактивность-маркеров-объектов-на-подложке-карты)
