### ISSUE TITLE
не обновляются метки на карте

### ISSUE THREAD

**Issue by smartfox87** [PNKBizz/vue-yandex-maps#21]
использую
"vue": "^3.2.0",
"vue-yandex-maps": "^1.0.4"
пример кода
https://disk.yandex.com/d/OLiNcUHoT7VHow
не обновляются метки на карте при обновлении данных приходящих из пропсов на живом сайте, но при этом если я поставлю setTimeout на пару сек и в нем отфильтрую массив меток на тестовых данных локальной сборки, то метки обновляются
https://monosnap.com/file/0b22qavex0Om3fAn3JdHTHR9Cq3j85
как видно на видео компоненты маркеров обновляются, но на карте изменений нет

**Comment by PNKBizz** [comment]
Нужен рабочий код в репозитории или песочнице

**Comment by drev74** [comment]
> Нужен рабочий код в репозитории или песочнице

You don't need an example. You have a hardcoded marker [here](https://github.com/PNKBizz/vue-yandex-maps/blob/d2c02dcb6fa69a6a779255e72a97f22179c8492a/src/Marker.ts#L84). Redesign is required to delete an old marker and create a new one on coord update

**Comment by PNKBizz** [comment]
Shame on me. @drev74 thanx a lot.

**Comment by drev74** [comment]
@PNKBizz thanks for fixing this promptly. 

I tested your fix and it works. However, the UX is very poor comparing to 0x version. 
The marker moves instantly like a teleport on the map, which breaks a normal user perception of the movement. In 0x marker and map update  is smooth and enjoyable. I'm having issues with some events too. I'll dig into this soon

**Comment by PNKBizz** [comment]
I'v added flying on map in ver. 1.0.7. Also I'v added map's prop `panOptions` to configure this behaviour

**Comment by drev74** [comment]
@PNKBizz Yes the `v1.0.7` fix seems to have a UX just right :smiley: Thanks for a prompt fix
