### ISSUE TITLE
после изменения центра карты пропадает карта

### ISSUE THREAD

**Issue by smartfox87** [PNKBizz/vue-yandex-maps#22]
после изменения центра карты при помощи метода инстанса карты setCenter пропадает карта, если перетащить карту вручную она появляется
[пример кода и проблемы](https://codesandbox.io/s/zen-swartz-viicd7?file=/src/App.vue)

**Comment by PNKBizz** [comment]
На 659 строчке обращайтесь напрямую к инстансу, без `this`:
```
mapObject.setCenter([30, 50], 16);
```

**Comment by smartfox87** [comment]
помогло, спасибо. только пришлось сохранить инстанс карты так 
window.mapObject = mapObject;
чтобы потом иметь к нему доступ из других методов

**Comment by PNKBizz** [comment]
Зачем же в window сохранять? Сохраняйте в this, как было. Но конкретно в вашем кейсе обращайтесь напрямую к mapObject

**Comment by smartfox87** [comment]
в том то и дело что при сохранении в this все ломается, видимо добавляемая vue реактивность ломает функционал яндекс карты. с window все ок

**Comment by PNKBizz** [comment]
Интересно. А если не объявлять в mapObject в data заранее? Тогда реактивности не будет и это будет просто поле объекта.

**Comment by smartfox87** [comment]
это помогло
