### ISSUE TITLE
здесь доступна переменная ymaps

### ISSUE THREAD

**Issue by ixard** [PNKBizz/vue-yandex-maps#25]
При попытке добавить в ymaps.geoObjects.add(objectManager) - ошибка Cannot read properties of undefined (reading 'add')
И так везде. Ни настроить, ни добавить объекты.
Переменную в консоли вижу - сделать ничего не могу.

**Comment by PNKBizz** [comment]
geoObjects - свойство карты, а ymaps - глобальная переменная API Я.Карт. Карту можно получить по событию `created`. https://vue-yandex-maps.github.io/new-docs/guide/map.html#%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D1%8F
