### ISSUE TITLE
Если window.ymaps уже загружен ранее, то ничего не происходит

### ISSUE THREAD

**Issue by zt50tz** [PNKBizz/vue-yandex-maps#36]
Кажется, что для того, чтобы все завелось, и модуль правильно обработал наличие уже загруженного `ymaps` нужно в файл `utils.ts` на строке `52` поменять

`if (window.ymaps) return res(true);`

на

```
if (window.ymaps){
      emitter.ymapReady = true;
      emitter.$emit('scriptIsLoaded');
      return res(true);
}
```

К сожалению, у меня не получилось нормально скомпилировать проект, поэтому отправлять pull request страшно :)

**Comment by PNKBizz** [comment]
Спасибо за репорт. Проверю в выходные и выпущу фикс.

**Comment by zt50tz** [comment]
— Есть сайт, который работает сам по себе (без vue).
— В определенный момент, пользователь может загрузить vue приложение внутри сайта в котором может происходить загрузка карт.
— Если на сайте уже были загружены Яндекс карты, то `yandex-map` не отображается, потому что карты уже загружены, но `emitter.ymapReady=false` по умолчанию и он не меняется.

Я попробую подготовить код простого примера и загрузить его.

**Comment by zt50tz** [comment]
https://codesandbox.io/s/21lprg?file=/public/index.html

— Нажимаем на кнопку "show vue map" - ничего не происходит
<img width="271" alt="Screenshot 2023-03-04 at 20 40 19" src="https://user-images.githubusercontent.com/33315115/222925632-9775c235-7f60-4889-9835-03bd93ee4f26.png">

— Если закомментировать строки с 23 по 39 в файле index.html, то при нажатии на кнопку все загрузится
<img width="279" alt="Screenshot 2023-03-04 at 20 40 46" src="https://user-images.githubusercontent.com/33315115/222925640-68aabe9e-59c5-4c38-a9ba-d9607378a0e6.png">

— Наверное, лучше все таки по другому написать в utils.ts

```
if (window.ymaps){
      if (!emitter.ymapReady) {
          emitter.ymapReady = true;
          emitter.$emit('scriptIsLoaded');
      }
      return res(true);
}
```

**Comment by PNKBizz** [comment]
Ага, отлично. Принято. 👌
