### ISSUE TITLE
Передача инстанса карты и работа с ним в другом компоненте

### ISSUE THREAD

**Issue by Ramsly** [PNKBizz/vue-yandex-maps#41]
При инициализации карты, получаю ее инстанс. Передаю его в другой компонент, при клике на кнопку "Указать местоположение" хочу добавить на карту маркер через переменную ymaps, но этого не происходит. Но если я при инициализации карты, без передачи в другой компонент поставлю маркер через ymaps, все работает. Как работать с инстансом карты в других компонентах и с любыми events?

**Comment by PNKBizz** [comment]
Выложите пример на гитхаб или в песочницу

**Comment by Ramsly** [comment]
> При инициализации карты, получаю ее инстанс. Передаю его в другой компонент, при клике на кнопку "Указать местоположение" хочу добавить на карту маркер через переменную ymaps, но этого не происходит. Но если я при инициализации карты, без передачи в другой компонент поставлю маркер через ymaps, все работает. Как работать с инстансом карты в других компонентах и с любыми events?

Кстати, что интересно, попробовал поработать с инстансом карты в том же компоненте, где я его и получаю, все работает. Даже с работой на нажатие кнопки в другой ф-ии

Из-за этого декомпозировать проект не особо хочется)

**Comment by PNKBizz** [comment]
`<SideNav :mapInstance="mapInstance" />`

**Comment by Ramsly** [comment]
> `<SideNav :mapInstance="mapInstance" />`

Сделал так, жму на кнопку, прилетает ошибка

`Uncaught TypeError: t.getType is not a function
    at Proxy.equals (full-b666dd375fb5cdae12a82507a986c8a4c9b518cd.js:1040:307)
    at Proxy.testShapeChange (full-b666dd375fb5cdae12a82507a986c8a4c9b518cd.js:559:4814)
    at Proxy.setParentElement (full-b666dd375fb5cdae12a82507a986c8a4c9b518cd.js:559:4672)
    at Proxy.destroyLayout (full-b666dd375fb5cdae12a82507a986c8a4c9b518cd.js:832:1990)
    at Proxy._destroyLayout (full-b666dd375fb5cdae12a82507a986c8a4c9b518cd.js:830:4501)
    at Proxy.destroy (full-b666dd375fb5cdae12a82507a986c8a4c9b518cd.js:830:5040)
    at Proxy.destroyView (full-b666dd375fb5cdae12a82507a986c8a4c9b518cd.js:785:3073)
    at Proxy._clearView (full-b666dd375fb5cdae12a82507a986c8a4c9b518cd.js:785:3006)
    at Proxy.removeFromMap (full-b666dd375fb5cdae12a82507a986c8a4c9b518cd.js:785:1114)
    at Proxy.removeFromMap (full-b666dd375fb5cdae12a82507a986c8a4c9b518cd.js:784:1133)`

**Comment by Ramsly** [comment]
> `console.error(error);` уберите

Тестил просто. Также есть проблемы с построением маршрута, с определением геолокации

**Comment by Ramsly** [comment]
> > `console.error(error);` уберите
> 
> Тестил просто. Также есть проблемы с построением маршрута, с определением геолокации

Скорее всего криворукий я, но хочу понять в чем проблема

**Comment by Ramsly** [comment]
Может я не совсем понимаю как пользоваться events в geoObjects? Я беру код полностью из яндекс документации

`ymaps.route(['Южное Бутово', 'Москва, метро Парк Культуры'], {
    multiRoute: true
}).done(function (route) {
    route.options.set("mapStateAutoApply", true);
    this.mapInstance.geoObjects.add(route);
}, function (err) {
    throw err;
}, this);`

Меняю на инстанс своей карты `this.mapInstance.geoObjects.add(route);` тоже не срабатывает

**Comment by Ramsly** [comment]
Вот фрагмент кода, когда при @created="onInit", карта инициализируется и сразу строится маршрут

**Comment by PNKBizz** [comment]
Нужна ссылка на codesandbox

**Comment by Ramsly** [comment]
Все тут же https://codesandbox.io/p/sandbox/peredacha-instansa-v-drugoy-komponent-ll2px0

**Comment by PNKBizz** [comment]
Нужно разбираться, пока не готов ответить. В выходные посмотрю

**Comment by Ramsly** [comment]
Хорошо, спасибо большое, буду ждать ответа!

**Comment by Ramsly** [comment]
Кстати еще замечание, даже когда карта только инициализировалась на `@create="onInit"` и вместо

 e.geoObjects.add(route);

прописать

this.mapInstance.geoObjects.add(route);

то маршрут также не построится

onInit(e) {
      this.mapInstance = e;
      console.log(e)
      console.log(this.mapInstance)
      ymaps
        .route(["Южное Бутово", "Москва, метро Парк Культуры"], {
          multiRoute: true,
        })
        .done(
          function (route) {
            route.options.set("mapStateAutoApply", true);
            e.geoObjects.add(route); ВОТ ТУТ
            console.log(e);
          },
          function (err) {
            throw err;
          },
          this
        );
    }

**Comment by Ramsly** [comment]
> Нужно разбираться, пока не готов ответить. В выходные посмотрю

Здравствуйте, ну что, вы пока не разбирались с проблемой?
