### ISSUE TITLE
Проблема с работой инстанса карты

### ISSUE THREAD

**Issue by Ramsly** [PNKBizz/vue-yandex-maps#42]
Здравствуйте, продублирую ошибку тут, так как она не решена и не является закрытой. Работать с инстансом карты невозможно, этот функционал необходим с работой карт. Вот [проблема](https://github.com/PNKBizz/vue-yandex-maps/issues/41). 

Ссылка на песочницу: https://codesandbox.io/p/sandbox/peredacha-instansa-v-drugoy-komponent-ll2px0

P.S Спасибо за ваш труд! Как бы я мог поддержать проект?

**Comment by Ramsly** [comment]
Мне стоит расчитывать на ответ, либо закрывать вопрос и пользоваться дефолтными картами через доку яндекса? Просто функционал очень нужен на данный момент и особо долго ждать не могу к сожалению. Не хочется отказываться пользоваться вашим решением

**Comment by PNKBizz** [comment]
Сегодня постараюсь проверить

**Comment by Ramsly** [comment]
> Сегодня постараюсь проверить

Спасибо большое!

**Comment by PNKBizz** [comment]
В общем штука в том, что инстанс карты нельзя делать реактивным. При этом ломается внутренняя логика Я.Карт. Т.е. в вашем примере можно сделать так https://codesandbox.io/p/sandbox/peredacha-instansa-v-drugoy-komponent-forked-5m3fk3?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A62%2C%22endLineNumber%22%3A42%2C%22startColumn%22%3A62%2C%22startLineNumber%22%3A42%7D%5D

**Comment by Ramsly** [comment]
> В общем штука в том, что инстанс карты нельзя делать реактивным. При этом ломается внутренняя логика Я.Карт. Т.е. в вашем примере можно сделать так https://codesandbox.io/p/sandbox/peredacha-instansa-v-drugoy-komponent-forked-5m3fk3?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A62%2C%22endLineNumber%22%3A42%2C%22startColumn%22%3A62%2C%22startLineNumber%22%3A42%7D%5D

Большущее спасибо! Протестил, все работает. Если что, создам issue
