### ISSUE TITLE
:options в YandexMap?

### ISSUE THREAD

**Issue by pPitohu** [PNKBizz/vue-yandex-maps#43]
Смотрел доки, как ограничить область видимости карты, чтобы за пределы нельзя было уйти и нашел, в оф. доках, но увидел, что  при использовании библиотеки нельзя добавить опции..

Хотел бы попросить добавить, если еще есть поддержка этой либы.

![image](https://user-images.githubusercontent.com/59769228/233646632-1002b539-9aac-47e6-9982-b49e78aa103b.png)

**Comment by pPitohu** [comment]
#44

**Comment by PNKBizz** [comment]
Добавлено в 1.0.9. Спасибо за участие!

**Comment by PNKBizz** [comment]
Можешь вторую багу отдельным issue завести? Желательно с примером в песочнице
