### ISSUE TITLE
[bug] Реактивность маркеров

### ISSUE THREAD

**Issue by pPitohu** [PNKBizz/vue-yandex-maps#46]
Я правда не уверен, связано это с реактивностью маркеров или чем-то другим, пытался форкать репо и сделать что-то свое, костыли и прочее, но ничего не помогало.

Ссылка на песочницу, где воспроизводится:
https://codesandbox.io/p/sandbox/nifty-neco-121dvo

STR:
Достаточно включить любой фильтр, отобразится 2 маркера, однако должен быть отображен один маркер, я вывожу прям на страницу информацию, сколько должно быть маркеров и сколько в массиве для вывода, сори что все в одном файле, однако да, временем не обеспечен..

В общем, проблема: Маркеры не фильтруются корректно, а именно: отображается 2 маркера, когда в массиве лишь один и больше нету, вероятно - кэшируется, баллун тоже пустой будет, т.к. по сути этого маркера нет, но он есть, и в итоге на карте их не 2, а вообще 3, хотя должен быть один. Да, над этим надо подумать, но надеюсь мысль понятна..

**Comment by dmitry53** [comment]
> , вероятно - кэшируется

тоже столкнулся с этим, если включить кластеризацию, кол-во элементов на одной координате будет расти

**Comment by pPitohu** [comment]
> > , вероятно - кэшируется
> 
> тоже столкнулся с этим, если включить кластеризацию, кол-во элементов на одной координате будет расти

Не думаю, что это связано с кластеризацией, т.к. в моем примере (в песочнице) там даже нет кластера) Просто маркеры и карта, все равно настакивается

**Comment by PNKBizz** [comment]
В выходные постараюсь посмотреть

**Comment by dmitry53** [comment]
> > > , вероятно - кэшируется
> > 
> > 
> > тоже столкнулся с этим, если включить кластеризацию, кол-во элементов на одной координате будет расти
> 
> Не думаю, что это связано с кластеризацией, т.к. в моем примере (в песочнице) там даже нет кластера) Просто маркеры и карта, все равно настакивается

В твою песочницу добавил вывод кластера, потыкал фильтры. Цифры с кластерами продолжают расти при клике на фильтры. Т.е. точки создаются повторно
![image](https://user-images.githubusercontent.com/2632988/235085818-5d45f552-8c63-4a30-9c60-4bdf905da247.png)

**Comment by pPitohu** [comment]
> В твою песочницу добавил вывод кластера, потыкал фильтры. Цифры с кластерами продолжают расти при клике на фильтры. Т.е. точки создаются повторно ![image](https://user-images.githubusercontent.com/2632988/235085818-5d45f552-8c63-4a30-9c60-4bdf905da247.png)

Кластеры просто показывают число точек настаканное, наглядно, циферкой)
Но они стакаются и так, без кластера, через девтулзы можно посмотреть, сколько ymaps-places элементов на странице, именно html, не vue devtools, так что скорее не в кластере проблема. Но в нем другая проблема, что не отображает точки.

![image](https://user-images.githubusercontent.com/59769228/235145264-e00db178-7b8c-4485-8d29-d57575002bbd.png)

**Comment by dmitry53** [comment]
@pPitohu как костыль, можно скрывать точки через visible: true | false у YandexMarker в options

**Comment by pPitohu** [comment]
> @pPitohu как костыль, можно скрывать точки через visible: true | false у YandexMarker в options

Увы, нельзя)
Я пробовал и v-if, и v-show, и модифицировать компонент, форкнув репозиторий и добавив туда проп isVisible, через options, но они не реактивные, ну или ни на что не влияют, в общем, не работает.

**Comment by PNKBizz** [comment]
Fixed in ver. 1.1.0
