### ISSUE TITLE
Пустой балун при одинаковых координатах  в кластере

### ISSUE THREAD

**Issue by dmitry53** [PNKBizz/vue-yandex-maps#47]
Использую кластеризацию, есть точки с одинаковыми координатами. При клике, открывается пустой шаблон без информации по точкам. Как можно добавить кастомный шаблон?

https://codesandbox.io/p/sandbox/tender-ride-bubwb7?file=%2Fsrc%2FApp.vue

**Comment by pPitohu** [comment]
Форкнул мою песочницу?)

**Comment by dmitry53** [comment]
Есть отличный пример для версии 0.х, но как его применить в v1

**Comment by PNKBizz** [comment]
Посмотрю на выходных и отпишусь вам

**Comment by PNKBizz** [comment]
Все реализуется через API Я.Карт
https://codesandbox.io/p/sandbox/sleepy-booth-xw7mf5?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A41%2C%22endLineNumber%22%3A56%2C%22startColumn%22%3A41%2C%22startLineNumber%22%3A56%7D%5D

**Comment by Dante3003** [comment]
Всем доброго времени суток, извините что пищу в закрытой теме но я не могу понять как передать кастомный компонент в балун от сластера @PNKBizz  подскажите пожалуйста.
