### ISSUE TITLE
Открытие балуна маркера программно

### ISSUE THREAD

**Issue by Irina2512** [PNKBizz/vue-yandex-maps#50]
Есть карта с отрисоваными на ней маркерами, балуны к маркерам беруться из компонента при помощи слота. 
<yandex-map :key="mapKey" :coordinates="mapCenter" :zoom="11" @created="initMap">
        <yandex-marker v-for="pickupPoint in this.tariffModule.filtered.pickupPoints"
                       :key="pickupPoint.id"
                       :coordinates="pickupPoint.coordinates"
                       :marker-id="pickupPoint.id"
                       :options="getIconSettings(pickupPoint)"
                       @click="setActivePickupPoint(pickupPoint)"
        >
          <template #component>
            <list-item-description :pickup-point="pickupPoint" :full-form="true"></list-item-description>
          </template>
        </yandex-marker>
</yandex-map>
Возможно ли по кнопке вне карты открывать балун выбранного маркера?
Пробовала получить доступ к инстансу карты через @created="initMap", но не вижу в нем списка маркеров.
Также указывала ref='markers' и пыталась обратиться к маркеру так, но тоже не помогло.

**Comment by PNKBizz** [comment]
Посмотрю в выходные

**Comment by Irina2512** [comment]
спасибо)

**Comment by Irina2512** [comment]
Еще попробовала так:
<yandex-map :key="mapKey" :coordinates="mapCenter" :zoom="zoom" @created="initMap" >
      <yandex-clusterer :options="clusterOptions">
        <yandex-marker v-for="pickupPoint in this.tariffModule.filtered.pickupPoints"
                       :key="pickupPoint.id"
                       :coordinates="pickupPoint.coordinates"
                       :marker-id="pickupPoint.id"
                       @click="setActivePickupPoint(pickupPoint)"
                       :ref="'marker-' + pickupPoint.id"
        >
          <template #component>
            <list-item-description :pickup-point="pickupPoint" :full-form="true"></list-item-description>
          </template>
        </yandex-marker>
      </yandex-clusterer>
    </yandex-map>

<script>
...
methods: {
    openBalloon(pickupPointId) {
         this.$refs['marker-' + pickupPointId].events.fire('click');
    }
}
</script>
но тоже не сработало, причем ошибок не выдает, но и балун не открывает :(

**Comment by PNKBizz** [comment]
Можете сделать пример в песочнице? На выходных не получилось воспроизвести

**Comment by Irina2512** [comment]
https://codesandbox.io/s/stoic-rgb-fbr7l8?file=/src/App.vue
Когда делала пример в песочнице, обращение к маркеру через ссылку сработало ( this.$refs['marker-' + pickupPointId].events.fire('click'); )
Но хотелось бы работать с элементами карты через инстанс, а в нем ничего кроме координат вытащить не смогла(
Пробовала обращаться к маркерам через instanceMap.geoObjects

**Comment by PNKBizz** [comment]
instanceMap.geoObjects возвращает вам кластер в вашем случае. В нем нужно уже пробираться к маркерам

**Comment by Irina2512** [comment]
Спасибо) Нужный балун получилось открыть так:
`let markers = this.map.geoObjects.get(0).getGeoObjects();
for (let i in markers) {
    if (markers[i].properties.get('markerId') === this.selectedMarker) {
        markers[i].balloon.open();
    }
}`

**Comment by Irina2512** [comment]
В способе выше только одна беда - если маркеры объединены в кластер и отображаются вот так:
[https://drive.google.com/file/d/1bWy9T9PRRkFpZ0MorujBQLtoQZSC46KI/view?usp=drive_link](url), то я не могу обратиться к этому маркеру (видимо потому что он не прорисован на карте), но в списке он есть. Как можно обойти эту проблему?
