### ISSUE TITLE
Дублирование точек на карте и странная отрисовка данных

### ISSUE THREAD

**Issue by volvi77** [PNKBizz/vue-yandex-maps#9]
Добрый день!
В первую очередь, большое спасибо за ваш продукт!

Итак, проблема.

Есть компонент карты:
![image](https://user-images.githubusercontent.com/107562146/185254167-8b633837-b383-435c-8b99-2bcc3eaa21b5.png)

Карта вставляется в компонент текущей страницы:
![image](https://user-images.githubusercontent.com/107562146/185248281-abf7ae5c-c5dc-4551-b366-4aadbe7a1a98.png)

Входной параметр "items" у компонента карты получает массив объектов с сервера через переменную "mapBuildings". Выглядит это вот так:
![image](https://user-images.githubusercontent.com/107562146/185250110-33287540-bfd6-4be3-8760-4e5153dcc427.png)

Пытаюсь динамически отрисовывать объекты на карте, в зависимости от применяемых фильтров.
Карта работает отлично на первом рендеринге, но вскоре начинается беда. В приложении предусмотрена система фильтров. 
- Когда применяются выбранные фильтры и кол-во объектов на карте **уменьшается** по сравнению с предыдущим запросом, то карта отрисовывает объекты отлично. 
- Если после применения фильтров, объектов необходимо отрисовать **столько-же**, сколько и в предыдущий запрос, карта никак не изменяет положение объектов (то есть, грубо говоря, не реагирует на фильтры)
- Если же объектов **больше**, чем в предыдущий запрос (даже на 1), то отрисовываются вообще все объекты, которые были отрисованы в текущей сессии пользователя, на всех фильтрациях.

Отмечу, что количество объектов в devtools для Vue всегда корректное, а вот меток на карте больше:
![image](https://user-images.githubusercontent.com/107562146/185253608-49dc102a-17f0-4c4d-bab1-3141ec6baaa5.png)
и
![image](https://user-images.githubusercontent.com/107562146/185253705-11ef0d27-2cb1-41c8-a599-dc57438b4249.png)

Решение нашел следующее:
![image](https://user-images.githubusercontent.com/107562146/185251983-5feba9de-4f9f-42fc-9b3a-ac463950de61.png)
и
![image](https://user-images.githubusercontent.com/107562146/185252333-ecab69e7-42e1-4eb0-852d-1f8021dad8a0.png)

Таким образом, благодаря "v-if" и "this.mapBuildings = undefined" пока пользователь ожидает отрисовки объектов, карта исчезает, а когда ответ от сервера приходит, перерисовывается. Объекты, в таком случае, обновляются нормально, в соответствие с фильтрами. Естественно, решение не конечное, а скорее помогает приблизиться к проблеме, и очень не хочется отказываться от вашего прекрасного продукта из-за этой проблемы.

Заранее спасибо за ответ и успехов!

upd upd upd upd ...

**Comment by PNKBizz** [comment]
Добрый день! 
Для начала попробуйте у YandexMarker проставить [уникальный `key`](https://v3.ru.vuejs.org/ru/api/special-attributes.html#key), возможно это решит проблему

**Comment by volvi77** [comment]
Большущее спасибо! Нашел решение, опишу тут, возможно, будет полезно. Или, может, вы увидите какой-то способ решить проблему иначе из моего опыта.

:key, действительно, почти решает проблему аналогичным способом, как и v-if.
Карта перерисовывается корректно и фильтры применяются. 
Но, к сожалению, перерисовывается вся карта, в то время, как на втором проекте используется objectManager и при изменении фильтров не перерисовывает всю карту, а меняет координаты точек.

А, если быть точнее: 
1) Точки добавляются в коллекцию -> добавляются на карту;
2) Запрос на сервер за данными точек;
3) Точки удаляются из коллекции ( .removeAll() );
4) Ответ от сервера;
5) Точки отрисовываются на карте;

Ршение на скриншоте:
![image](https://user-images.githubusercontent.com/107562146/185354715-ff0d9f72-1325-4477-ac13-84123ca16b8d.png)

Не уверен, как это работает внутри, но я так понимаю, что при использовании YandexCollection с ключом, привязанным к объекту данных, Vue.js понимает, что надо "обновить" компонент и рефрешит слой с точками, при каждом обновлении массива с данными.

Важный момент! **Если я привязываю :key к длине массива данных, то, когда (n - 1) и (n) запросы присылают одинаковое количество элементов, то коллекция не перерисовывается** (наверное, это логично, просто, стоит учитывать при использовании :key).

Я бы хотел финансово поддержать Ваши труды, подскажите, пожалуйста, как я могу это сделать?

И еще раз спасибо за ответ!

**Comment by PNKBizz** [comment]
Спасибо за ваш вклад в тестирование ) Это лучшая поддержка. Если что-то еще будет всплывать, обязательно пишите!
